// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlnvvwbttbpqbaebxmvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsbnZ2d2J0dGJwcWJhZWJ4bXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNDIwOTAsImV4cCI6MjA1MTgxODA5MH0.QoxwiunShxsCngPTZUbS9nxEWWwnsaN4CtwF43Pnxw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);